import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="author" content="kkchengaf (John)"/>
          <meta name="description"
            content="Playing multiple YouTube videos at the same time. 
            Watching multiple live streams with live chat support. 
            Adjust video layouts to best fit your preference!"/>
            <meta name="google-site-verification" content="aGqaF2FqE0Z8Vl8z9-x4_QSSrOARrvSJsTggaoFUV_8" />


            <title>Multiple Embedded Youtube Player</title>
            <script src="https://www.youtube.com/iframe_api" type="text/javascript">
            </script>
            
          </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
